Bikeshop.create(name: 'Thompson’s Boat Center', address: '2900 Virginia Ave, NW', location_id: 97, phone: '202-333-9543', bike_rental: true, website: 'http://www.thompsonboatcenter.com/')
Bikeshop.create(name: 'Bike the Sites', address: '901 G Street NW', location_id: 98, phone: '202-966-8662', bike_rental: true, website: 'http://www.bikethesites.com/')
Bikeshop.create(name: 'Big Wheel Bikes', address: '1034 33rd St NW', location_id: 97, phone: '202-337-0254', bike_rental: true, website: 'http://www.bigwheelbikes.com/')
Bikeshop.create(name: 'Revolution Cycles', address: '3411 M St NW', location_id: 98, phone: '202-965-3601', bike_rental: false, website: 'http://revolutioncycles.com/storelocator/clarendon-2.htm')
Bikeshop.create(name: 'Fletcher’s Boat Center', address: '4940 Canal Rd NW', location_id: 98, phone: '202-244-0461', bike_rental: true, website: 'http://www.fletcherscove.com/')
Bikeshop.create(name: 'Brunswick Hardware', address: '302 W Potomac St', location_id: 77, phone: '301-834-9207', bike_rental: false, website: 'http://discoverbrunswickmd.com/?dir-item=brunswick-hardware-and-sporting-goods')
Bikeshop.create(name: 'C&O Canal Biking', address: '24 W Potomac St', location_id: 77, phone: '301-834-5180', bike_rental: true, website: '')
Bikeshop.create(name: 'River & Trail Outfitters', address: '604 Valley Rd', location_id: 75, phone: '301-695-5177', bike_rental: true, website: 'http://www.rivertrail.com/index.php')
Bikeshop.create(name: 'Outfitter at Harpers Ferry', address: '106 Potomac St', location_id: 74, phone: '888-535-2087', bike_rental: true, website: 'http://www.theoutfitteratharpersferry.com/')
Bikeshop.create(name: 'River Riders', address: '408 Allstadts Hill Rd.', location_id: 74, phone: '800-326-7238', bike_rental: true, website: 'http://www.riverriders.com/')
Bikeshop.create(name: 'Reels & Wheels', address: '17328 Taylors Lndg Rd', location_id: 70, phone: '301-432-7281', bike_rental: false, website: 'https://www.facebook.com/pages/Reels-and-Wheels/316422291795284?rf=162853357065733')
Bikeshop.create(name: 'River City Cycles', address: '22 N Conococheague', location_id: 62, phone: '301-223-6733', bike_rental: false, website: 'http://rivercitycyclesinc.com/')
Bikeshop.create(name: 'C&O Bicycle', address: '9 S Pennsylvania Av', location_id: 54, phone: '301-678-6665', bike_rental: true, website: '')
Bikeshop.create(name: 'Cycles & Things', address: '165 N Centre St', location_id: 35, phone: '301-722-5496', bike_rental: false, website: '')
Bikeshop.create(name: 'Mountainside Bike Trs', address: '108 Decatur St', location_id: 35, phone: '800-459-0510', bike_rental: true, website: '')
Bikeshop.create(name: 'Adventure Sport (24/7)', address: '115 E Main St', location_id: 33, phone: '301-689-0345', bike_rental: true, website: '')
Bikeshop.create(name: 'Rockwood Trail House', address: '131 Rockdale Rd', location_id: 29, phone: '814-916-2453', bike_rental: true, website: '')
Bikeshop.create(name: 'Allegheny Recumbents', address: 'P.O. Box 160', location_id: 25, phone: '888-395-BIKE', bike_rental: true, website: '')
Bikeshop.create(name: 'Riversport', address: '885 River Rd.', location_id: 25, phone: '800-216-6991', bike_rental: true, website: '')
Bikeshop.create(name: 'Wilderness Voyageurs', address: 'PA381, 130 Garrett St', location_id: 24, phone: '800-272-4141', bike_rental: true, website: '')
Bikeshop.create(name: 'Lrl Highlands Rvr Tours', address: 'Sherman St', location_id: 24, phone: '800-472-3846', bike_rental: true, website: '')
Bikeshop.create(name: 'White Water Adv', address: 'Negley St', location_id: 24, phone: '724-329-8850', bike_rental: true, website: '')
Bikeshop.create(name: 'Ohiopyle Rec Rentals', address: 'PA381, Commercial St', location_id: 24, phone: '800-723-8669', bike_rental: true, website: '')
Bikeshop.create(name: 'Ohiopyle Trading Post', address: 'Negley St', location_id: 24, phone: '724-329-1450', bike_rental: true, website: '')
Bikeshop.create(name: 'Bikes Unlimited', address: '503 W. Crawford Av', location_id: 22, phone: '724-628-2453', bike_rental: true, website: '')
Bikeshop.create(name: 'Youghiogheny Rentals', address: '112 Railroad St', location_id: 19, phone: '724-529-2552', bike_rental: true, website: '')
Bikeshop.create(name: 'Cedar Creek Station', address: 'Cedar Creek Park', location_id: 14, phone: '724-872-5586', bike_rental: true, website: '')
Bikeshop.create(name: 'West Newton Bikes', address: '106 W Main St', location_id: 10, phone: '724-872-2185', bike_rental: true, website: '')
Bikeshop.create(name: 'River City Junction', address: '242 Sandy Dr', location_id: 6, phone: '412-754-0976', bike_rental: true, website: '')
Bikeshop.create(name: 'Boston Shoppes', address: '1903 Donner St', location_id: 5, phone: '412-751-6695', bike_rental: true, website: '')
Bikeshop.create(name: 'Trailside Treasures', address: '1910 Donner St', location_id: 5, phone: '412-896-6015', bike_rental: true, website: '')
Bikeshop.create(name: 'Burke Lee\'s', address: '2422 St David Dr', location_id: 4, phone: '412-754-1490', bike_rental: true, website: '')
Bikeshop.create(name: 'Golden Triangle Bike', address: 'on trail at 1st Ave', location_id: 1, phone: '412-600-0675', bike_rental: true, website: '')
Bikeshop.create(name: 'REI, Southside Works', address: '1 block from trail', location_id: 1, phone: '412-488-9410', bike_rental: false, website: '')
Bikeshop.create(name: 'Biketek Pittsburgh', address: '5839 Forbes Ave', location_id: 1, phone: '412-521-6448', bike_rental: true, website: '')
Bikeshop.create(name: 'Gatto Cycling & Fitness', address: '7501 Penn Ave', location_id: 1, phone: '412-731-9200', bike_rental: true, website: '')
Bikeshop.create(name: 'Top Gear', address: '986 Penn Circle South Suite 204', location_id: 1, phone: '412-362-8735', bike_rental: false, website: '')
